version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Django app Dockerfile
    ports:
      - 8000:8000  # Adjust the port as needed
    depends_on:
      - postgres-db
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres-db:5432/myproject  # Use the connection URL for Django
    command: bash -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=myproject

  

